all:
	@(cd go-echod; make)
	@(cd go-httpd; make)
	@(cd httpd-handler; make)
	@(cd gin-server; make)
	@(cd grpc; make)

clean:
	@(cd go-echod; make clean)
	@(cd go-httpd; make clean)
	@(cd httpd-handler; make clean)
	@(cd gin-server; make clean)
	@(cd grpc; make clean)
